fix: assignment error (#62)
* fix: assignment error

warning: data definition has no type or storage class
warning: type defaults to 'int' in declaration of 'n_cpu_name' [-Wimplicit-int]
error: conflicting types for 'n_cpu_name'; have 'int'

Variables may only be declared at global scope, not assigned.

Fix adds type prefix to change from assignment to declaration.

* chore: Add `blues` user to dev container